#pragma config(Sensor, S1,     ,               sensorLightActive)
#pragma config(Sensor, S2,     ,               sensorCOLORFULL)
#pragma config(Motor,  motorA,           ,             tmotorNXT, openLoop, encoder)
#pragma config(Motor,  motorB,           ,             tmotorNXT, openLoop, encoder)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


task main()
{
	int white = 62;
	int color = 42; // Blue
	float threshold = (white + color)/2;
	float Kp = 3.25;
	int power = 40;
	while(1)
	{
		int error = (SensorValue[S1] - threshold)/2;
		int correction = error * Kp;
		motor[motorB] = power - correction;
		motor[motorC] = power + correction;
	}
}
